// Central language strings for all WorkHud pages
window.workhudLangStrings = {
  sv: {
    allGames: 'Alla spel i världen',
    myGames: 'Mina spel',
    home: 'Hem',
    by: 'av',
    open: 'Testa',
    edit: 'Redigera',
    noGames: 'Inga spel hittades.',
    create: 'Skapa...',
    me: 'Jag',
    save: 'Spara projekt',
    load: 'Ladda projekt',
    loadGame: 'Ladda spel',
    publish: 'Publicera spel',
    run: '▶',
    stop: '■',
    askName: 'Vad ska spelet heta?',
    askAuthor: 'Vad heter du? (Författare)',
    published: 'Spelet är nu publicerat och syns för alla på startsidan!',
    loaded: 'Spelet laddat!',
    notFound: 'Spelet hittades inte!',
    back: 'Tillbaka',
    promptLoad: 'Vad heter spelet du vill ladda?',
    studio: 'Studion',
    test: 'Testa',
    game: 'Spel',
    blocks: 'Kodbitar',
    language: 'Språk',
    menuHome: 'Hem',
    menuMyGames: 'Mina spel',
    menuStudio: 'Studion',
    menuTest: 'Testa',
    itemsInList: 'det som finns i listan:'
  },
  en: {
    allGames: 'All games in the world',
    myGames: 'My games',
    home: 'Home',
    by: 'by',
    open: 'Test',
    edit: 'Edit',
    noGames: 'No games found.',
    create: 'Create...',
    me: 'Me',
    save: 'Save project',
    load: 'Load project',
    loadGame: 'Load game',
    publish: 'Publish game',
    run: '▶',
    stop: '■',
    askName: 'What is the game name?',
    askAuthor: 'What is your name? (Author)',
    published: 'Game is now published and visible for everyone on the home page!',
    loaded: 'Game loaded!',
    notFound: 'Game not found!',
    back: 'Back',
    promptLoad: 'What is the name of the game you want to load?',
    studio: 'Studio',
    test: 'Test',
    game: 'Game',
    blocks: 'Blocks',
    language: 'Language',
    menuHome: 'Home',
    menuMyGames: 'My games',
    menuStudio: 'Studio',
    menuTest: 'Test',
    itemsInList: 'items in the list:'
  }
};
